//===-----------------------------*  C#  *---------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------===//

using System;

namespace Invar
{

    public static class RecvRequest<T, R>
    {
        static public event Action<T, R> Event;

        static public void Raise(T req, R resp)
        {
            if (null != Event)
            {
                Event(req, resp);
            }
        }
    }

    public static class RecvResponse<T>
    {
        static public event Action<T> Event;

        static public void Raise(T o)
        {
            if (null != Event)
            {
                Event(o);
            }
        }
    }

    public static class RecvNotify<T>
    {
        static public event Action<T> Event;

        static public void Raise(T o)
        {
            if (null != Event)
            {
                Event(o);
            }
        }
    }

}