#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ===------------------------------*  Python  *------------------------------===
#             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
# ===------------------------------------------------------------------------===

from TestProtocProtoc2C import Protoc2C
try:
    from cStringIO import StringIO
except:
    from StringIO import StringIO
from InvarCodec import DataWriter
from InvarCodec import DataReader

class TestServerTimeN2C(object):

    """服务器通知客户端"""
    CRC32_ = 0x85E08773
    SIZE_  = 16

    __slots__ = (
        '_protocId',
        '_protocCRC',
        '_protoc2C',
        '_time',
        '_hotfix')
   #__slots__

    def __init__(self):
        self._protocId  = 65530
        self._protocCRC = TestServerTimeN2C.CRC32_
        self._protoc2C  = None
        self._time      = -1
        self._hotfix    = None
   #def __init__

    def __str__(self):
        s = StringIO()
        s.write(u'{')
        s.write(u' ')
        s.write(u'TestServerTimeN2C')
        s.write(u',')
        s.write(u' ')
        s.write(u'protocId')
        s.write(u':')
        s.write(unicode(self._protocId))
        s.write(u',')
        s.write(u' ')
        s.write(u'protocCRC')
        s.write(u':')
        s.write(unicode(self._protocCRC))
        s.write(u',')
        s.write(u' ')
        s.write(u'protoc2C')
        s.write(u':')
        if self._protoc2C is None:
            s.write(u'null')
        else:
            s.write(u'<')
            s.write(u'Protoc2C')
            s.write(u'>')
        s.write(u',')
        s.write(u' ')
        s.write(u'time')
        s.write(u':')
        s.write(unicode(self._time))
        s.write(u',')
        s.write(u' ')
        s.write(u'hotfix')
        s.write(u':')
        if self._hotfix is None:
            s.write(u'null')
        else:
            s.write(u'[')
            s.write(str(len(self._hotfix)))
            s.write(u']')
        s.write(u' ')
        s.write(u'}')
        result = s.getvalue()
        s.close()
        return result
   #def __str__

    def __len__(self):
        size = TestServerTimeN2C.SIZE_
        if self._protoc2C is not None:
            size += len(self._protoc2C)
        if self._hotfix is not None:
            size += 4
            for (k1,v1) in self._hotfix.items():
                size += len(k1)
                size += len(v1)
        return size
   #def __len__

    def read(r):
        self._protocId = r.readUInt16()
        self._protocCRC = r.readUInt32()
        if CRC32 != self._protocCRC:
            raise InvarError(499, "Protoc read error: CRC32 is mismatched.", 499)
        protoc2CExists = r.readInt8()
        if 0x01 == protoc2CExists:
            if self._protoc2C == None:
                self._protoc2C = Protoc2C()
            self._protoc2C.read(r)
        elif 0x00 == protoc2CExists:
            self._protoc2C = None
        else:
            raise InvarError(497, 'Protoc read error: The value of \'protoc2CExists\' is invalid.')
        self._time = r.readInt64()
        hotfixExists = r.readInt8()
        if 0x01 == hotfixExists:
            if self._hotfix == None:
                self._hotfix = dict()
            lenHotfix = r.readUInt32()
            num = 0
            while num < lenHotfix:
                num += 1
                k1 = r.readString()
                v1 = r.readString()
                self._hotfix[k1] = v1
        elif 0x00 == hotfixExists:
            self._hotfix = None
        else:
            raise InvarError(498, 'Protoc read error: The value of \'hotfixExists\' is invalid.')
   #def read

    def write(w):
        w.writeUInt16(self._protocId)
        w.writeUInt32(self._protocCRC)
        if self._protoc2C != None:
            w.writeUInt8(0x01)
            self._protoc2C.write(w)
        else:
            w.writeUInt8(0x00)
        w.writeInt64(self._time)
        if self._hotfix != None:
            w.writeUInt8(0x01)
            w.writeUInt32(len(self._hotfix))
            for (k1,v1) in self._hotfix.items():
                w.writeString(k1)
                w.writeString(v1)
        else:
            w.writeUInt8(0x00)
   #def write

#class TestServerTimeN2C

if '__main__' == __name__:
    print('dir(TestServerTimeN2C()) =>\n' + '\n'.join(dir(TestServerTimeN2C())))
    print('TestServerTimeN2C.__doc__ => ' + TestServerTimeN2C.__doc__)
    print('TestServerTimeN2C.__len__ => ' + str(len(TestServerTimeN2C())))
    print('TestServerTimeN2C.__str__ => ' + str(TestServerTimeN2C()))
