/*===-----------------------------*  C#  *---------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------===*/

namespace Test.Abc {

/// 性别的枚举类型.
public enum Gender : int
{
    NONE   = -1,
    MALE   = 10, // Enum male.
    FEMALE = 20, // Enum female.

} // enum Gender
} //namespace: Test.Abc