/*===----------------------------*  Java  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------===*/
package test.protoc;

import java.io.DataInput;
import java.io.DataInputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.LinkedHashMap;
import java.util.Map;

/** 服务端请求,客户端响应 */
public final class TestHeartBeatR2S
implements
invar.InvarCodec.ProtocResponse,
invar.InvarCodec.BinaryDecode,
invar.InvarCodec.BinaryEncode,
invar.InvarCodec.XMLEncode
{
    static public final long CRC32 = 0xD651F662;

    static public TestHeartBeatR2S Create() {
        return new TestHeartBeatR2S();
    }

    private java.lang.Integer            protocId   ;/* [AutoAdd] ProtocolID */
    private java.lang.Long               protocCRC  ;/* [AutoAdd] Protocol CRC32 */
    private java.lang.Integer            protocError;/* [AutoAdd] Protocol error code */
    private Protoc2S                     protoc2S   ;/* [AutoAdd] 客户端请求的公共数据 */
    private LinkedHashMap<String,String> hotfix     ;/* [AutoAdd] Hotfix */

    public TestHeartBeatR2S()
    {
        protocId    = 65533;
        protocCRC   = CRC32;
        protocError = 0;
        protoc2S    = null;
        hotfix      = null;
    }

    public TestHeartBeatR2S reuse()
    {
        protocId = 65533;
        protocCRC = CRC32;
        protocError = 0;
        if (protoc2S != null) {
            protoc2S.reuse();
        }
        if (hotfix != null) {
            hotfix.clear();
        }
        return this;
    }

    /** [AutoAdd] ProtocolID */
    @invar.InvarRule(T="uint16", S="f0")
    public java.lang.Integer getProtocId() { return protocId; }

    /** [AutoAdd] Protocol CRC32 */
    @invar.InvarRule(T="uint32", S="f1")
    public java.lang.Long getProtocCRC() { return protocCRC; }

    /** [AutoAdd] Protocol error code */
    @invar.InvarRule(T="uint16", S="f2")
    public java.lang.Integer getProtocError() { return protocError; }

    /** [AutoAdd] 客户端请求的公共数据 */
    @invar.InvarRule(T="test.protoc.Protoc2S", S="f3")
    public Protoc2S getProtoc2S() { return protoc2S; }

    /** [AutoAdd] Hotfix */
    @invar.InvarRule(T="map<string,string>", S="f4")
    public LinkedHashMap<String,String> getHotfix() { return hotfix; }

    /** [AutoAdd] Protocol error code */
    @invar.InvarRule(T="uint16", S="f2")
    public TestHeartBeatR2S setProtocError(java.lang.Integer value) { this.protocError = value; return this; }

    /** [AutoAdd] 客户端请求的公共数据 */
    @invar.InvarRule(T="test.protoc.Protoc2S", S="f3")
    public TestHeartBeatR2S setProtoc2S(Protoc2S value) { this.protoc2S = value; return this; }

    /** [AutoAdd] Hotfix */
    @invar.InvarRule(T="map<string,string>", S="f4")
    public TestHeartBeatR2S setHotfix(LinkedHashMap<String,String> value) { this.hotfix = value; return this; }

    public TestHeartBeatR2S copy (TestHeartBeatR2S from)
    {
        if (this == from || from == null) {
            return this;
        }
        protocId = from.protocId;
        protocCRC = from.protocCRC;
        protocError = from.protocError;
        if (from.protoc2S != null) {
            protoc2S.copy(from.protoc2S);
        } else {
            protoc2S = null;
        }
        if (from.hotfix != null) {
            hotfix.clear();
            hotfix.putAll(from.hotfix);
        } else {
            hotfix = null;
        }
        return this;
    } //copyFrom(...)

    public void read(InputStream from) throws IOException
    {
        this.read((DataInput)new DataInputStream(from));
    }

    public void read(DataInput from) throws IOException
    {
        protocId = from.readUnsignedShort();
        protocCRC = from.readInt() & 0xFFFFFFFFL;
        protocError = from.readUnsignedShort();
        if (from.readByte() == (byte)0x01) {
            protoc2S.read(from);
        }
        hotfix.clear();
        if (from.readByte() == (byte)0x01) {
            Long lenHotfix = from.readInt() & 0xFFFFFFFFL;
            for (Long iHotfix = 0L; iHotfix < lenHotfix; ++iHotfix) {
                java.lang.String k1 = from.readUTF();
                java.lang.String v1 = from.readUTF();
                hotfix.put(k1,v1);
            }
        }
    }

    public void write(OutputStream from) throws IOException
    {
        this.write((DataOutput)new DataOutputStream(from));
    }

    public void write(DataOutput dest) throws IOException
    {
        dest.writeShort(protocId);
        dest.writeInt(protocCRC.intValue());
        dest.writeShort(protocError);
        if (protoc2S != null) {
            dest.writeByte((byte)0x01);
            protoc2S.write(dest);
        } else {
            dest.writeByte((byte)0x00);
        }
        if (hotfix != null) {
            dest.writeByte((byte)0x01);
            dest.writeInt(hotfix.size());
            for (Map.Entry<java.lang.String,java.lang.String> hotfixIter : hotfix.entrySet()) {
                java.lang.String k1 = hotfixIter.getKey();
                dest.writeUTF(k1);
                java.lang.String v1 = hotfixIter.getValue();
                dest.writeUTF(v1);
            }
        } else {
            dest.writeByte((byte)0x00);
        }
    }

    public StringBuilder toStringXML (String name)
    {
        StringBuilder result = new StringBuilder();
        StringBuilder attrs  = new StringBuilder();
        StringBuilder nodes  = new StringBuilder();
        attrs.append(" protocId=\"");
        attrs.append(protocId.toString()); attrs.append("\"");
        attrs.append(" protocCRC=\"");
        attrs.append(protocCRC.toString()); attrs.append("\"");
        attrs.append(" protocError=\"");
        attrs.append(protocError.toString()); attrs.append("\"");
        if (protoc2S != null) {
            nodes.append(protoc2S.toStringXML("protoc2S"));
        }
        if (hotfix != null && hotfix.size() > 0) {
            nodes.append("<hotfix>");
            for (Map.Entry<java.lang.String,java.lang.String> hotfixIter : hotfix.entrySet()) {
                java.lang.String k1 = hotfixIter.getKey();
                nodes.append("<k1 value=\"");
                nodes.append(k1);
                nodes.append("\">");
                java.lang.String v1 = hotfixIter.getValue();
                nodes.append("<v1 value=\"");
                nodes.append(v1);
                nodes.append("\">");
            }
            nodes.append("</hotfix>");
        }
        result.append("<"); result.append(name); result.append(attrs);
        if (nodes.length() == 0) {
            result.append("/>");
        } else {
            result.append(">");
            result.append(nodes);
            result.append("</"); result.append(name); result.append(">");
        }
        return result;
    } //TestHeartBeatR2S::toStringXML (String name)

    public String toString ()
    {
        StringBuilder result = new StringBuilder();
        result.append("{ ");
        result.append(getClass().getName());
        result.append(", protocId:");
        result.append(protocId.toString());
        result.append(", protocCRC:");
        result.append(protocCRC.toString());
        result.append(", protocError:");
        result.append(protocError.toString());
        result.append(", protoc2S:");
        if (protoc2S != null) {
            result.append("<Protoc2S>");
        } else {
            result.append("null");
        }
        result.append(", hotfix:");
        if (hotfix != null) {
            result.append("[" + hotfix.size() + "]");
        } else {
            result.append("null");
        }
        result.append(" }");
        return result.toString();
    } //TestHeartBeatR2S::toString ()

}

