//*==---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------==*//

#ifndef Invar_h
#define Invar_h

#import <stdint.h>

typedef struct _ResponseBytes {
    const void * bytes;
    int32_t      length;
    int32_t      error;
    uint16_t     request;
    uint16_t     response;
} ResponseBytes;

void          HandleNotify2S   (const void * const, int32_t);
void          HandleNotify2C   (const void * const, int32_t);
void          HandleResponse2S (const void * const, int32_t);
void          HandleResponse2C (const void * const, int32_t);
ResponseBytes HandleRequest2S  (const void * const, int32_t);
ResponseBytes HandleRequest2C  (const void * const, int32_t);

#endif /* Invar_h */
