//===---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------===//

#ifndef Invar_h
#define Invar_h

#import "DataWriter.h"
#import "DataReader.h"

@protocol InvarDecode

- (NSInteger)read:(DataReader *)r;

@end

@protocol InvarEncode

- (NSInteger)write:(DataWriter *)w;

@end


#endif /* Invar_h */
