//===---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------===//

#ifndef DataReader_h
#define DataReader_h

#import <Foundation/Foundation.h>

@interface DataReader : NSObject

+ (instancetype) CreateWithData:(const NSData * const)data;
+ (instancetype) CreateWithData:(const NSData * const)data andOffset:(NSUInteger)offset;
+ (instancetype) CreateWithBytes:(const void * const)bytes andLength:(NSUInteger)len;

- (int8_t)    readInt8   : (BOOL *)eof;
- (int16_t)   readInt16  : (BOOL *)eof;
- (int32_t)   readInt32  : (BOOL *)eof;
- (int64_t)   readInt64  : (BOOL *)eof;
- (uint8_t)   readUInt8  : (BOOL *)eof;
- (uint16_t)  readUInt16 : (BOOL *)eof;
- (uint32_t)  readUInt32 : (BOOL *)eof;
- (uint64_t)  readUInt64 : (BOOL *)eof;
- (float_t)   readFloat  : (BOOL *)eof;
- (double_t)  readDouble : (BOOL *)eof;
- (boolean_t) readBool   : (BOOL *)eof;
- (NSString*) readString : (BOOL *)eof;

- (uint16_t)  peekUInt16 : (BOOL *)eof;

@end

#endif /* DataReader_h */
