//*==---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------==*//

#ifndef INVARRUNTIME_H_
#define INVARRUNTIME_H_

#import "test_protoc_TestUserLoginR2C.h"
#import "test_protoc_TestUserLogin2S.h"
#import "test_protoc_TestUserLocationN2S.h"
#import "test_protoc_TestServerTimeN2C.h"
#import "test_protoc_TestHeartBeatR2S.h"
#import "test_protoc_TestHeartBeat2C.h"

typedef void (^RecvRequest)(id req, id resp);
typedef void (^RecvResponse)(id resp);
typedef void (^RecvNotify)(id ntf);
typedef void (^HandleError)(NSInteger err, uint16_t protoc);

@interface InvarRuntime : NSObject

@property (nonatomic, strong) RecvRequest  blockRecvRequest;
@property (nonatomic, strong) RecvResponse blockRecvResponse;
@property (nonatomic, strong) RecvNotify   blockRecvNotify;
@property (nonatomic, strong) HandleError  blockHandleError;

+ (instancetype) shared;
+ (id<InvarEncode>)HandleProtocAsServer:(DataReader * const)input Protoc:(uint16_t *)req Error:(uint16_t *)code;
+ (id<InvarEncode>)HandleProtocAsClient:(DataReader * const)input Protoc:(uint16_t *)req Error:(uint16_t *)code;

@end

/****************************************************************************** HandleProtocAsServer */

/* 客户端请求,服务端响应 */
extern void HandleTestUserLogin2S(TestUserLogin2S *, TestUserLoginR2C *);
#define HandleTestUserLogin2S [[self shared] blockRecvRequest]

/* 客户端通知服务端 */
extern void HandleTestUserLocationN2S(TestUserLocationN2S *);
#define HandleTestUserLocationN2S [[self shared] blockRecvNotify]

/* 服务端请求,客户端响应 */
extern void HandleTestHeartBeatR2S(TestHeartBeatR2S *);
#define HandleTestHeartBeatR2S [[self shared] blockRecvResponse]

/******************************************************************************/

/****************************************************************************** HandleProtocAsClient */

/* 客户端请求,服务端响应 */
extern void HandleTestUserLoginR2C(TestUserLoginR2C *);
#define HandleTestUserLoginR2C [[self shared] blockRecvResponse]

/* 服务器通知客户端 */
extern void HandleTestServerTimeN2C(TestServerTimeN2C *);
#define HandleTestServerTimeN2C [[self shared] blockRecvNotify]

/* 服务端请求,客户端响应 */
extern void HandleTestHeartBeat2C(TestHeartBeat2C *, TestHeartBeatR2S *);
#define HandleTestHeartBeat2C [[self shared] blockRecvRequest]

/******************************************************************************/

#import "ProtocHandlers.h"


#endif /* INVARRUNTIME_H_ */
