//*==---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------==*//

#ifndef TESTXYZCONFLICT_H_
#define TESTXYZCONFLICT_H_

#import <Foundation/NSValue.h>
#import <Foundation/NSString.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSDictionary.h>
#import "InvarProtoc.h"

/*  */
@interface Test_Xyz_Conflict : NSObject <NSCopying, InvarEncode, InvarDecode, InvarEncodeJSON>

- (double_t             ) pi    ; /*  */
- (NSMutableDictionary *) hotfix; /* [AutoAdd] Hotfix */

- (Test_Xyz_Conflict *) setPi    : (double_t             ) value; /* 0 double */
- (Test_Xyz_Conflict *) setHotfix: (NSMutableDictionary *) value; /* 1 map<string,string> */

@end /* @interface Test_Xyz_Conflict */

#endif /* TESTXYZCONFLICT_H_ */
