//*==---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------==*//

#ifndef TEST_XYZ_CONFLICT_H_
#define TEST_XYZ_CONFLICT_H_

#import <Foundation/NSValue.h>
#import <Foundation/NSString.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSDictionary.h>
#import "Invar.h"

/*  */
@interface test_xyz_Conflict : NSObject <NSCopying, InvarEncode, InvarDecode, InvarEncodeJSON>

- (double_t             ) pi    ; /*  */
- (NSMutableDictionary *) hotfix; /* [AutoAdd] Hotfix */

- (test_xyz_Conflict *) setPi    : (double_t             ) value; /* 0 double */
- (test_xyz_Conflict *) setHotfix: (NSMutableDictionary *) value; /* 1 map<string,string> */

@end /* @interface test_xyz_Conflict */

#endif /* TEST_XYZ_CONFLICT_H_ */
