//*==---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------==*//

#ifndef TESTXYZCONFIGROOT_H_
#define TESTXYZCONFIGROOT_H_

#import <Foundation/NSString.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSDictionary.h>
#import "TestXyzTestNest.h"
#import "TestXyzTestList.h"
#import "TestXyzTestDict.h"
#import "TestXyzInfoX.h"
#import "TestAbcInfo.h"
#import "InvarProtoc.h"

/*  */
@interface ConfigRoot : NSObject <NSCopying, InvarEncode, InvarDecode, InvarEncodeJSON>

- (NSString            *) revision; /*  */
- (TestList            *) list    ; /*  */
- (TestDict            *) dict    ; /*  */
- (TestNest            *) nest    ; /*  */
- (Info                *) info    ; /*  */
- (InfoX               *) infox   ; /*  */
- (NSMutableDictionary *) hotfix  ; /* [AutoAdd] Hotfix */

- (ConfigRoot *) setRevision: (NSString            *) value; /* f0 string */
- (ConfigRoot *) setList    : (TestList            *) value; /* f1 Test.Xyz.TestList */
- (ConfigRoot *) setDict    : (TestDict            *) value; /* f2 Test.Xyz.TestDict */
- (ConfigRoot *) setNest    : (TestNest            *) value; /* f3 Test.Xyz.TestNest */
- (ConfigRoot *) setInfo    : (Info                *) value; /* f4 Test.Abc.Info */
- (ConfigRoot *) setInfox   : (InfoX               *) value; /* f5 Test.Xyz.InfoX */
- (ConfigRoot *) setHotfix  : (NSMutableDictionary *) value; /* f6 map<string,string> */

@end /* @interface ConfigRoot */

#endif /* TESTXYZCONFIGROOT_H_ */
