//*==---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------==*//

#ifndef TEST_PROTOC_TESTHEARTBEAT2C_H_
#define TEST_PROTOC_TESTHEARTBEAT2C_H_

#import <Foundation/NSString.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSDictionary.h>
#import "test_protoc_Protoc2C.h"
#import "InvarProtoc.h"

/* 服务端请求,客户端响应 */
@interface TestHeartBeat2C : NSObject <NSCopying, InvarEncode, InvarDecode, InvarEncodeJSON>

- (uint16_t             ) protocId ; /* [AutoAdd] ProtocolID */
- (uint32_t             ) protocCRC; /* [AutoAdd] Protocol CRC32 */
- (Protoc2C            *) protoc2C ; /* [AutoAdd] 服务端响应的公共数据 */
- (NSMutableDictionary *) hotfix   ; /* [AutoAdd] Hotfix */

- (TestHeartBeat2C *) setProtoc2C : (Protoc2C            *) value; /*  test.protoc.Protoc2C */
- (TestHeartBeat2C *) setHotfix   : (NSMutableDictionary *) value; /*  map<string,string> */

@end /* @interface TestHeartBeat2C */

#endif /* TEST_PROTOC_TESTHEARTBEAT2C_H_ */
