//*==---------------------------*  Obj-C  *--------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------==*//

#ifndef TEST_XYZ_TESTDICT_H_
#define TEST_XYZ_TESTDICT_H_

#import <Foundation/NSValue.h>
#import <Foundation/NSString.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSDictionary.h>
#import "test_abc_Gender.h"
#import "test_abc_Custom.h"
#import "Invar.h"

/* 测试基本的映射类型 */
@interface TestDict : NSObject <NSCopying, InvarEncode, InvarDecode, InvarEncodeJSON>

- (NSMutableDictionary *) dictI08    ; /* 有符号的8位整数 */
- (NSMutableDictionary *) dictI16    ; /* 有符号的16位整数 */
- (NSMutableDictionary *) dictI32    ; /* 有符号的32位整数 */
- (NSMutableDictionary *) dictI64    ; /* 有符号的64位整数 */
- (NSMutableDictionary *) dictU08    ; /* 无符号的8位整数 */
- (NSMutableDictionary *) dictU16    ; /* 无符号的16位整数 */
- (NSMutableDictionary *) dictU32    ; /* 无符号的32位整数 */
- (NSMutableDictionary *) dictU64    ; /* 无符号的64位整数 */
- (NSMutableDictionary *) dictSingle ; /* 单精度浮点小数 */
- (NSMutableDictionary *) dictDouble ; /* 双精度浮点小数 */
- (NSMutableDictionary *) dictBoolean; /* 布尔值 */
- (NSMutableDictionary *) dictString ; /* 字符串 */
- (NSMutableDictionary *) dictEnum   ; /* 枚举值 */
- (NSMutableDictionary *) dictStruct ; /* 自定义结构 */
- (NSMutableDictionary *) hotfix     ; /* [AutoAdd] Hotfix */

- (TestDict *) setHotfix     : (NSMutableDictionary *) value; /* 14 map<string,string> */

@end /* @interface TestDict */

#endif /* TEST_XYZ_TESTDICT_H_ */
