<?php
/*===----------------------------*  PHP 5  *-------------------------------===//
//
//             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
//
//===----------------------------------------------------------------------===*/

namespace test\abc;

abstract class Gender
{
    const NONE   = -1;
    const MALE   = 10; // Enum male
    const FEMALE = 20; // Enum female
}
